version: '3.9'
services:
  frontend:
    build: .
    image: echo-web-frontend:latest
    command: bash -c "yarn start & yarn cypress run && kill $$!"
    # Don't start tests before backend is up.
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend
    ports:
      - '3000:3000'
    environment:
      BACKEND_HOST: backend:8080

  backend:
    # Runs tests against backend master branch.
    # This might change (?)
    build: https://github.com/echo-webkom/echo-web-backend.git#master
    image: echo-web-backend:latest
    # Don't start backend before database is up.
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    ports:
      - '8080:8080'
    # Check if backend is ready, and insert bedpres for testing.
    healthcheck:
      test: ["CMD-SHELL", "./test_scripts/submit_bedpres -z -p 8080 -x hemmelig -s bedriftspresentasjon-med-bekk -o 5 -r 2021-05-06T16:46+01:00 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      DEV: ja
      DATABASE_HOST: database
      AUTH_KEY: hemmelig

  database:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - '5432:5432'
    # Check if database is ready.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
