name: Build CMS
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/cms/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/cms/yarn.lock') }}

      - name: Install dependencies
        run: |
          cd cms
          yarn --frozen-lockfile --ignore-scripts

      - name: Build with yarn
        run: |
          cd cms
          yarn build
