name: Cypress
on:
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io

permissions:
  packages: write
  actions: read

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend with cache & push
        run: |
          cd frontend
          docker build \
            --cache-from "$REGISTRY/frontend" \
            -t "$REGISTRY/frontend:$GITHUB_SHA" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg SANITY_DATASET=$SANITY_DATASET \
            .
          docker push "$REGISTRY/frontend" --all-tags
        env:
          DOCKER_BUILDKIT: 1
          REGISTRY: ${{ env.REGISTRY }}
          SANITY_DATASET: testing

      - name: Build backend with cache & push
        run: |
          cd backend
          docker build \
            --cache-from "$REGISTRY/backend" \
            -t "$REGISTRY/backend:$GITHUB_SHA" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
          docker push "$REGISTRY/backend" --all-tags
        env:
          DOCKER_BUILDKIT: 1
          REGISTRY: ${{ env.REGISTRY }}

      - name: Run Cypress end-to-end tests
        run: docker compose up --exit-code-from=frontend --attach=frontend
        env:
          REGISTRY: ${{ env.REGISTRY }}
          SANITY_DATASET: testing
          ADMIN_KEY: admin-passord
          NEXTAUTH_SECRET: very-secret-string-123
