name: Cypress production
on:
  pull_request:
    branches: master

jobs:
  cypress_tests_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v2

    - name: Checkout backend repository
      uses: actions/checkout@v2
      with:
        repository: echo-webkom/echo-web-backend
        path: backend
        ref: master

    - name: Set up environment
      run: |
        echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> .env
        echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env
        echo "CONTENTFUL_ENVIRONMENT_ID=$CONTENTFUL_ENVIRONMENT_ID" >> .env
        echo "BEDKOM_KEY=$BEDKOM_KEY" >> .env
        echo "WEBKOM_KEY=$WEBKOM_KEY" >> .env
        echo "BRANCH=$BRANCH" >> .env
        echo "FRONTEND_TAG=$TAG" >> .env
        echo "BACKEND_TAG=$TAG" >> .env
      env:
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID_TESTING }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_TESTING }}
        CONTENTFUL_ENVIRONMENT_ID: testing
        BEDKOM_KEY: bedkom-passord
        WEBKOM_KEY: webkom-passord
        BRANCH: master
        TAG: latest-prod

    - name: Run Cypress end-to-end tests against production backend
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        compose_file: docker-compose.ci.yaml
