name: Docker push image
on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io

permissions:
  packages: write
  actions: read

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend with cache & push
        run: |
          cd frontend
          docker build \
            --cache-from "$REGISTRY/frontend" \
            -t "$REGISTRY/frontend:$TAG" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg SANITY_DATASET=$SANITY_DATASET \
            .
          docker push "$REGISTRY/frontend" --all-tags
        env:
          DOCKER_BUILDKIT: 1
          REGISTRY: ${{ env.REGISTRY }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          TAG: latest

      - name: Build backend with cache & push
        run: |
          cd backend
          docker build \
            --cache-from "$REGISTRY/backend" \
            -t "$REGISTRY/backend:$TAG" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
          docker push "$REGISTRY/backend" --all-tags
        env:
          DOCKER_BUILDKIT: 1
          REGISTRY: ${{ env.REGISTRY }}
          TAG: latest
