name: Kotest

on:
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io

jobs:
  kotest_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache
        run: |
          cd backend
          docker build \
            --cache-from "$REGISTRY/backend" \
            -t "$REGISTRY/backend:$GITHUB_SHA" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
          docker push "$REGISTRY/backend" --all-tags
        env:
          DOCKER_BUILDKIT: 1
          REGISTRY: ${{ env.REGISTRY }}
          TAG: ${{ env.TAG }}

      - name: Run Kotest tests with Docker Compose
        run: |
          cd backend
          ./scripts/test -t kotest
        env:
          ADMIN_KEY: admin-passord
