name: Deploy to Sanity Studio
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/cms/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/cms/yarn.lock') }}

      - name: Install dependencies
        run: |
          cd cms
          yarn --frozen-lockfile

      - name: Deploy to Sanity
        run: |
          cd cms
          yarn sanity deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_STUDIO_API_DATASET: production
